### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
### code here
import numpy as np

In [28]:
print('Original array:')
np1=np.array([[ 3,  2, np.nan,  1],[10, 12, 10,  9],[ 5, np.nan,  1, np.nan]])
print(np1)
print()
print("Find the missing data of the said array:")
print(np.isnan(np1))


Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [32]:
### code here 
np1=np.arange(9).reshape(3,3)
np2=np.arange(10,19).reshape(3,3)
print(np1)
print(np2)
print(np.equal(np1,np2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[False False False]
 [False False False]
 [False False False]]


In [33]:
np1=np.arange(9).reshape(3,3)
np2=np.arange(9).reshape(3,3)
print(np1)
print(np2)
print(np.equal(np1,np2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [41]:
## code here
np1=np.arange(16).reshape(4,4)
print("Original array:",np1,sep="\n")
print("New array after swapping first and last rows of the said array:")
np1[[0,-1],:]=np1[[-1,0],:]
print(np1)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [42]:
#### code here
lists = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.array(lists))
tuples = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.array(tuples))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


###### 5. Write a NumPy program to find common values between two arrays.

In [44]:
### code here
array1 = np.array([10, 20, 40, 60])
print("Array1: ",array1)
array2 = np.array([10, 30, 40,70])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [10 20 40 60]
Array2:  [10 30 40 70]
Common values between two arrays:
[10 40]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [46]:
### code here
x = np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)
print("Reshape 3x2:")
print(x)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [2]:
### code here
ar = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(ar)
uniqueelements, countselements = np.unique(ar, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((uniqueelements, countselements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [4]:
### code here
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print()
print("New Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [5]:
### code here
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [8]:
## code here
arra = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra)
print("\nExtracted data: Third and fourth elements of the first and second rows ")
print(arra[0:2, 2:])


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [9]:
### code here
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-09-24
Today:  2022-09-25
Tomorrow:  2022-09-26


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [10]:
## code here
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))

First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
