## Creating Array

In [1]:
list1=list(range(40))
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]


In [1]:
import numpy as np

In [4]:
arr1=np.array(list1)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [6]:
tp=(1,2,3,4,5)

In [7]:
arr2=np.array(tp)
arr2

array([1, 2, 3, 4, 5])

In [7]:
arr2.ndim #shows dimensions

1

In [8]:
arr2.shape #how many elements in the array

(5,)

In [6]:
list2d=[[10,20,30],[40,50,60]]

arr2d=np.array(list2d)
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
arr2d.ndim

2

In [8]:
np.ndim(arr2d)

2

In [11]:
arr2d.shape

(2, 3)

In [12]:
arr2d[1][2]

60

In [10]:
list3d=[[10,20,30],[40,50,60]]
lists=np.array(list3d,ndmin=10)   #creates multidimension array
print(lists)
print(lists.ndim)

[[[[[[[[[[10 20 30]
         [40 50 60]]]]]]]]]]
10


In [1]:
%timeit [i**4 for i in range(1,8)]

3.79 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
%timeit np.arange(1,8)**4

2.78 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
x=np.arange(1,8)**4
print(x)

[   1   16   81  256  625 1296 2401]


## Creating array using functions

In [13]:
arr_1=np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr_1=np.arange(0,51,5)
arr_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
arr_1=np.arange(0,51,5,dtype='float')
arr_1

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [20]:
arr1=np.linspace(0,50,9)
arr1

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [24]:
arr1=np.linspace(0,50,9,dtype='int') #creates array with values in a specified interval
arr1

array([ 0,  6, 12, 18, 25, 31, 37, 43, 50])

In [21]:
arr1=np.ones(5)
arr1

array([1., 1., 1., 1., 1.])

In [30]:
arr1=np.ones((5,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
arr1=np.ones((5,4),dtype="int")
arr1
print(arr1.dtype)

int32


In [61]:
arr1=np.ones((5,4),dtype=np.int16)
print(arr1)
print('Data type :',arr1.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data type : int16


In [68]:
arr1=np.ones(5)
new=np.int_(arr1)
print(arr1)
print('Data type :',arr1.dtype)
print(new)
print('Data type :',new.dtype)

[1. 1. 1. 1. 1.]
Data type : float64
[1 1 1 1 1]
Data type : int32


In [66]:
arr1=np.ones((5,4),dtype='f')
print(arr1)
print('Data type :',arr1.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Data type : float32


In [27]:
arr1=np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [29]:
arr1=np.zeros((5,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arr1=np.full((5,5),10)
arr1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [34]:
arr1=np.diag([10,45,86])
arr1

array([[10,  0,  0],
       [ 0, 45,  0],
       [ 0,  0, 86]])

In [24]:
arr1=np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr1=np.random.random(4)  #gives random values between 0 to 1
arr1

array([0.26355147, 0.20741097, 0.80486792, 0.94032245])

In [34]:
arr1=np.random.rand(4)
arr1

array([0.34212434, 0.51978962, 0.48152522, 0.09179777])

In [31]:
arr1=np.random.rand(4,3)
arr1

array([[0.02829572, 0.76115677, 0.27017505],
       [0.27768451, 0.41280474, 0.83820344],
       [0.10829033, 0.19214261, 0.63088939],
       [0.26516288, 0.27332532, 0.27041698]])

In [36]:
var=np.random.randn(4,3) #gives random values close to 0(including -ve values)
var

array([[ 0.90428825, -0.9102062 , -0.29693547],
       [ 2.07825585,  0.6420246 , -0.08411301],
       [-0.5648593 , -0.19671426, -0.9994438 ],
       [-0.82653988, -0.18282388,  1.65051058]])

In [38]:
var1=np.random.ranf(5) #generates random values excluding 0
print(var1)

[0.09111877 0.90067273 0.85807655 0.6357938  0.3392424 ]


In [53]:
var2=np.random.randint(5,10,3) #generates random values between a given range[min,max,total value]
print(var2)

[5 8 6]


In [48]:
var2=np.random.randint(5,10) 
print(var2)

6


In [51]:
var2=np.random.randint(5) 
print(var2)

3


In [32]:
arrr=np.empty(4)
print(arrr)

[1. 1. 1. 1.]


In [29]:
arr=np.empty((4,3))
print(arr)

[[0.00779133 0.73200551 0.12909479]
 [0.14735194 0.38129177 0.11128325]
 [0.45299191 0.09463737 0.81107451]
 [0.13577023 0.99318996 0.6310047 ]]


## Slicing

In [2]:
arr1=np.diag([10,45,86])
arr1

array([[10,  0,  0],
       [ 0, 45,  0],
       [ 0,  0, 86]])

In [3]:
arr1[0:2,0:2]

array([[10,  0],
       [ 0, 45]])

In [4]:
arr1[1:,]

array([[ 0, 45,  0],
       [ 0,  0, 86]])

In [32]:
arr1[0::2,1::]

array([[ 0,  0],
       [ 0, 86]])

In [5]:
arr1[1,2]=10
arr1

array([[10,  0,  0],
       [ 0, 45, 10],
       [ 0,  0, 86]])

## Basic Arithmetic Operations

In [8]:
arr2

array([1, 2, 3, 4, 5])

In [9]:
narr=arr2+10
narr

array([11, 12, 13, 14, 15])

In [10]:
arr1

array([[10,  0,  0],
       [ 0, 45, 10],
       [ 0,  0, 86]])

In [11]:
arr1*5

array([[ 50,   0,   0],
       [  0, 225,  50],
       [  0,   0, 430]])

In [20]:
arr3=np.arange(9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr1

array([[10,  0,  0],
       [ 0, 45, 10],
       [ 0,  0, 86]])

In [18]:
arr1*arr3

array([[  0,   0,   0],
       [  0, 180,  50],
       [  0,   0, 688]])

In [35]:
arr=arr1.dot(arr3)
arr                #matrix multiplication

array([[  0,  10,  20],
       [195, 250, 305],
       [516, 602, 688]])

In [24]:
np.equal(arr1,arr3)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [25]:
np.array_equal(arr1,arr2)

False

In [27]:
a=np.arange(6).reshape(2,3)
print(a)

b=np.where(a<4)
#print(b)
a[b]

[[0 1 2]
 [3 4 5]]


array([0, 1, 2, 3])

In [12]:
a=np.arange(6).reshape(2,3)
print(a)
print()

b=np.where(a==4)  #gives index position
print(b) 

[[0 1 2]
 [3 4 5]]

(array([1], dtype=int64), array([1], dtype=int64))


In [13]:
var=np.array([1,2,3,4,6,7,8])

x=np.searchsorted(var,5)
print(x) #gives index position

4


In [18]:
var=np.array([1,2,3,4,6,7,8,9,10])

x=np.searchsorted(var,12,side='right')
print(x)

9


In [19]:
var=np.array([1,2,3,4,6,7,8])

x=np.searchsorted(var,[15,5,8])
print(x)

[7 4 6]


In [20]:
var=np.array([1,2,3,4,15,8,36,6,7,8])
print(np.sort(var))

[ 1  2  3  4  6  7  8  8 15 36]


In [16]:
var=np.array([1,2,3,4])
var1=np.array([1,2,3,4])

print(np.add(var,var1))
print(np.subtract(var,var1))
print(np.multiply(var,var1))
print(np.divide(var,var1))
print(np.mod(var,var1)) #'%' which gives reminder
print(np.power(var,var1))
print(np.reciprocal(var))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[0 0 0 0]
[  1   4  27 256]
[1 0 0 0]


In [5]:
print('Original array:')
np1=np.array([[0,1],[2,3]])
print(np1)
print("Sum of all elements:",np.sum(np1),sep="\n")
print("Sum of each column:",np.sum(np1,axis=0),sep="\n")
print("Sum of each row:",np.sum(np1,axis=1),sep="\n")

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [6]:
print("Original vectors:")
np1=np.array([4,5])
np2=np.array([7,10])
print(np1)
print(np2)
print("Inner product of said vectors:",np1.dot(np2),sep="\n")

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


## Arithmetic Functions

In [9]:
var=np.array([1,5,2,4,6,8,3,2])

print('Min :',np.min(var))
print('Max :',np.max(var))
print('Sqrt :',np.sqrt(var))

Min : 1
Max : 8
Sqrt : [1.         2.23606798 1.41421356 2.         2.44948974 2.82842712
 1.73205081 1.41421356]


In [6]:
var=np.array([1,5,2,4,6,8,3,2])

print('Max :',np.max(var),np.argmax(var)) #gives index number of max
print('Min :',np.min(var),np.argmin(var)) #gives index number of min

Max : 8 5
Min : 1 0


In [7]:
var=np.array([[2,3,9],[8,6,7]])
print(np.min(var,axis=0)) #column wise
print(np.min(var,axis=1)) #row wise

[2 3 7]
[2 6]


In [11]:
var1=np.array([2,3,4])

print(np.sin(var1))
print()
print(np.cos(var1))

[ 0.90929743  0.14112001 -0.7568025 ]

[-0.41614684 -0.9899925  -0.65364362]


In [12]:
var1=np.array([2,3,4])

print(np.cumsum(var1)) #cumulative sum

[2 5 9]


In [24]:
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[4 3 1 2 5]


In [25]:
var=np.array([1,2,3,4,5,5,2,4,4,4,8,8,45,19])
x=np.unique(var)
print(x)

[ 1  2  3  4  5  8 19 45]


In [5]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements,counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [26]:
var=np.array([1,2,3,4,5,5,2,4,4,4,8,8,45,19])
x=np.unique(var,return_index=True)
print(x)

(array([ 1,  2,  3,  4,  5,  8, 19, 45]), array([ 0,  1,  2,  3,  4, 10, 13, 12], dtype=int64))


In [27]:
var=np.array([1,2,3,4,5,5,2,4,4,4,8,8,45,19])
x=np.unique(var,return_index=True,return_counts=True)
print(x)

(array([ 1,  2,  3,  4,  5,  8, 19, 45]), array([ 0,  1,  2,  3,  4, 10, 13, 12], dtype=int64), array([1, 2, 1, 4, 2, 2, 1, 1], dtype=int64))


In [33]:
var=np.array([1,2,3,4,5,6])
x=np.reshape(var,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


In [34]:
var=np.array([1,2,3,4,5,6])
x=np.resize(var,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


In [36]:
var=np.array([1,2,3,4,5,6])
x=np.insert(var,2,40)    #to insert any value
print(x)

[ 1  2 40  3  4  5  6]


In [35]:
var=np.array([1,2,3,4,5,6])
x=np.insert(var,(2,3),40)
print(x)

[ 1  2 40  3 40  4  5  6]


In [38]:
var=np.array([[1,2,3],[4,5,6]])
x=np.insert(var,2,40,axis=0)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]]


In [39]:
var=np.array([[1,2,3],[4,5,6]])
x=np.insert(var,2,40,axis=1)
print(x)

[[ 1  2 40  3]
 [ 4  5 40  6]]


In [41]:
var=np.array([[1,2,3],[4,5,6]])
x=np.insert(var,2,[40,60],axis=1)
print(x)

[[ 1  2 40  3]
 [ 4  5 60  6]]


In [47]:
var=np.array([[1,2,3],[4,5,6]])
x=np.insert(var,2,[40,60,80],axis=0)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [40 60 80]]


In [48]:
var=np.array([1,2,3,4,5,6])
x=np.append(var,40)
print(x)

[ 1  2  3  4  5  6 40]


In [50]:
var=np.array([[1,2,3],[4,5,6]])
x=np.append(var,[[40,60,80]],axis=0)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [40 60 80]]


In [51]:
var=np.array([1,2,3,4,5,6])
x=np.append(var,40)
print(x)
print()
y=np.delete(x,6)      #to delete any value
print(y)

[ 1  2  3  4  5  6 40]

[1 2 3 4 5 6]


In [4]:
print("Original array:")
np1=np.arange(12,38)
print(np1)
np2=np.flip(np1)           #used to reverse an array
print('Reverse array:',np2,sep="\n")

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [7]:
print('Original array:')
np1=np.array([[ 3,  2, np.nan,  1],[10, 12, 10,  9],[ 5, np.nan,  1, np.nan]])
print(np1)
print()
print("Find the missing data of the said array:")
print(np.isnan(np1))  #finds the missing value

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


### Calculating Mean, Median

In [36]:
arr

array([[  0,  10,  20],
       [195, 250, 305],
       [516, 602, 688]])

In [37]:
np.mean(arr,axis=0)  #calculates mean column wise

array([237.        , 287.33333333, 337.66666667])

In [38]:
np.mean(arr,axis=1) #calculates mean row wise

array([ 10., 250., 602.])

In [39]:
np.median(arr,axis=0)  #calculates median column wise

array([195., 250., 305.])

In [40]:
np.median(arr,axis=1)  #calculates median row wise

array([ 10., 250., 602.])

### Read data from text file

In [57]:
dt=np.loadtxt('populations.txt',dtype='int')
dt

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500],
       [ 1903, 77400, 35200, 38200],
       [ 1904, 36300, 59400, 40600],
       [ 1905, 20600, 41700, 39800],
       [ 1906, 18100, 19000, 38600],
       [ 1907, 21400, 13000, 42300],
       [ 1908, 22000,  8300, 44500],
       [ 1909, 25400,  9100, 42100],
       [ 1910, 27100,  7400, 46000],
       [ 1911, 40300,  8000, 46800],
       [ 1912, 57000, 12300, 43800],
       [ 1913, 76600, 19500, 40900],
       [ 1914, 52300, 45700, 39400],
       [ 1915, 19500, 51100, 39000],
       [ 1916, 11200, 29700, 36700],
       [ 1917,  7600, 15800, 41800],
       [ 1918, 14600,  9700, 43300],
       [ 1919, 16200, 10100, 41300],
       [ 1920, 24700,  8600, 47300]])

In [44]:
dt.shape

(21, 4)

In [45]:
dt.ndim

2

In [62]:
p=dt[:,1:]
p

array([[30000,  4000, 48300],
       [47200,  6100, 48200],
       [70200,  9800, 41500],
       [77400, 35200, 38200],
       [36300, 59400, 40600],
       [20600, 41700, 39800],
       [18100, 19000, 38600],
       [21400, 13000, 42300],
       [22000,  8300, 44500],
       [25400,  9100, 42100],
       [27100,  7400, 46000],
       [40300,  8000, 46800],
       [57000, 12300, 43800],
       [76600, 19500, 40900],
       [52300, 45700, 39400],
       [19500, 51100, 39000],
       [11200, 29700, 36700],
       [ 7600, 15800, 41800],
       [14600,  9700, 43300],
       [16200, 10100, 41300],
       [24700,  8600, 47300]])

In [63]:
np.mean(p,axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [64]:
np.mean(p,axis=0,dtype='int')

array([34080, 20166, 42400])

In [65]:
p.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [66]:
np.sort(p,axis=0)

array([[ 7600,  4000, 36700],
       [11200,  6100, 38200],
       [14600,  7400, 38600],
       [16200,  8000, 39000],
       [18100,  8300, 39400],
       [19500,  8600, 39800],
       [20600,  9100, 40600],
       [21400,  9700, 40900],
       [22000,  9800, 41300],
       [24700, 10100, 41500],
       [25400, 12300, 41800],
       [27100, 13000, 42100],
       [30000, 15800, 42300],
       [36300, 19000, 43300],
       [40300, 19500, 43800],
       [47200, 29700, 44500],
       [52300, 35200, 46000],
       [57000, 41700, 46800],
       [70200, 45700, 47300],
       [76600, 51100, 48200],
       [77400, 59400, 48300]])

In [68]:
np.median(p,axis=0)

array([25400., 12300., 41800.])

### Reshaping the data

In [82]:
arr4=np.arange(9)    # 1D array
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
arr5=np.arange(9).reshape(3,3)  #makes any array to 2D array
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr6=np.arange(24).reshape(2,3,4)  #makes any array to 3D array
arr6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [78]:
arr6.reshape(3,8) #change 3D array to 2D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [85]:
arr5.T  #transpose of the array

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [84]:
arr5.flatten() #coverts any array to 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
arr5.ravel()  #coverts any array to 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
one=arr6.reshape(-1)  #coverts any array to 1D array
print(one)
print()
print(one.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

1


### Array Manipulation

In [3]:
arr1=np.array([10,20,30])
arr2=np.array([50,60,70])

In [4]:
arr_1=np.arange(1,10).reshape(3,3)
arr_2=np.arange(10,19).reshape(3,3)

In [6]:
np.concatenate((arr_1,arr_2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
np.concatenate((arr_1,arr_2),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [9]:
np.hstack((arr_1,arr_2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [10]:
np.vstack((arr_1,arr_2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
np.dstack((arr_1,arr_2)) #3D array

array([[[ 1, 10],
        [ 2, 11],
        [ 3, 12]],

       [[ 4, 13],
        [ 5, 14],
        [ 6, 15]],

       [[ 7, 16],
        [ 8, 17],
        [ 9, 18]]])

In [12]:
np.column_stack((arr_1,arr1))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [9]:
arr=np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
np.array_split(arr_1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [15]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [16]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [10]:
np.vsplit(arr,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [18]:
np.vsplit(arr,3)

ValueError: array split does not result in an equal division

## Matrix Operations

In [53]:
var=np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.inv(var))  #inverse of the matrix

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [59]:
var=np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,2))  #power of matrix (multiplication)
print()
print(np.linalg.matrix_power(var,0))  #gives identity matrix
print()
print(np.linalg.matrix_power(var,-3)) #inverse * power(multiplication)

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[-14.75    6.75 ]
 [ 10.125  -4.625]]


In [57]:
var=np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.det(var))  #determinant of matrix

[[1 2]
 [3 4]]

-2.0000000000000004


## Iterating of Numpy array

In [20]:
var=np.array([1,2,3,4,5])
print(var)
print()

for i in var:
    print(i)

[1 2 3 4 5]

1
2
3
4
5


In [21]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()

for i in var:
    print(i)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]


In [22]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()

for i in var:
    for j in i:
        print(j)

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [27]:
var=np.array([[4,5,8,9],[1,2,3,4]])
print(var)
print()
#'nditer' used to iterator
for i in np.nditer(var):
    print(i)

[[4 5 8 9]
 [1 2 3 4]]

4
5
8
9
1
2
3
4


In [30]:
var=np.array([[4,5,8,9],[1,2,3,4]])
print(var)
print()
#'ndenumerate' used to get index position of the elements
for i,d in np.ndenumerate(var):
    print(i,d)

[[4 5 8 9]
 [1 2 3 4]]

(0, 0) 4
(0, 1) 5
(0, 2) 8
(0, 3) 9
(1, 0) 1
(1, 1) 2
(1, 2) 3
(1, 3) 4
